server:
  port: 8081
spring:
  application:
    name: GXSHOPPING-PLAT

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      #因为注册中心配置了需要登陆才能访问，所以需要在配置注册中心这加上登陆账户和密码
      defaultZone: http://root:root@localhost:8761/eureka/
